version: '3.7'

services:
  deepftas:
    image: yue2388253/deepftas
    command: /bin/bash
    working_dir: /DeepFTAS
    volumes:
      - .:/DeepFTAS
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    stdin_open: true
    tty: true

